{
 "title": "Business if-else metrics",
 "tags": [
  "homework",
  "business"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Транзакции по веткам if-else (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (branch) (rate(business_transactions_total[1m]))",
     "legendFormat": "{{branch}}"
    }
   ]
  },
  {
   "title": "Транзакции по исходам (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (outcome) (rate(business_transactions_total[1m]))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Всего транзакций по веткам",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (branch) (business_transactions_total)",
     "legendFormat": "{{branch}}"
    }
   ]
  },
  {
   "title": "Длительность обработки p95 (сек)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(business_transaction_duration_seconds_bucket[5m])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Средняя сумма транзакции по веткам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum by (branch)(rate(business_transaction_amount_currency_sum[5m])) / sum by (branch)(rate(business_transaction_amount_currency_count[5m]))",
     "legendFormat": "{{branch}}"
    }
   ]
  }
 ]
}