name: seminar3-hw

services:
  postgres:
    image: postgres:15
    container_name: hw3-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pg_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: hw3-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    networks:
      - pg_net
    depends_on:
      postgres:
        condition: service_healthy

  app:
    build: ./app
    container_name: hw3-app
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/mydatabase
      DB_USER: admin
      DB_PASSWORD: password
    networks:
      - pg_net
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data:
  pgadmin_data:

networks:
  pg_net:
    driver: bridge
